### ISSUE TITLE
Contributing guide and what help is needed?

### ISSUE THREAD

**Issue by benjamingr** [jsIsrael/d3-epidemiology-timeline#1]
For those of us who don't use Telegram. If any such help is needed at all.

**Comment by Bnaya** [comment]
This repo is low-profile-but-not-secrete ATM

**Comment by benjamingr** [comment]
kk.

**Comment by benjamingr** [comment]
@Bnaya make it private then?

**Comment by urish** [comment]
Right now Elad is prototyping in Code Sandbox, he'll import the code later: https://pmgg8.csb.app/

It's okay to have this repo public

**Comment by shairez** [comment]
I've now added you to the team of this repo @benjamingr
